name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: make docker-image

      - name: run
        run: make run-container

      - name: publish
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_ORG: ${{ github.repository_owner }}
        run: make publish
